import React, { useState } from 'react';
import {
  Link as LinkIcon,
  CheckSquare,
  ExternalLink,
  Info,
} from 'lucide-react';
import { PracticalQuestionItem } from '../types';

interface PracticalTaskProps {
  question: PracticalQuestionItem;
  canvaLink?: string;
  notes?: string;
  onLinkChange: (link: string) => void;
  onNotesChange: (notes: string) => void;
}

export const PracticalTask: React.FC<PracticalTaskProps> = ({
  question,
  canvaLink = '',
  notes = '',
  onLinkChange,
  onNotesChange,
}) => {
  const [testedLink, setTestedLink] = useState(false);

  const isValidUrl =
    canvaLink.trim().length > 0 &&
    /^https?:\/\/.+/i.test(canvaLink.trim());

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-blue-600 font-bold uppercase tracking-widest text-xs">
            Practical Task 22
          </span>
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 bg-orange-50 text-orange-700 text-[10px] font-bold uppercase rounded border border-orange-200">
              Manual Evaluation
            </span>
            <span className="text-[11px] font-semibold text-slate-400">
              {question.marks} Marks
            </span>
          </div>
        </div>

        <h2 className="text-xl sm:text-2xl font-bold text-slate-800 leading-snug">
          {question.taskTitle}
        </h2>
        <p className="text-sm text-slate-600 leading-relaxed">
          {question.taskDescription}
        </p>
      </div>

      {/* Campaign Design Brief Box */}
      <div className="p-6 rounded-xl bg-slate-50 border border-slate-200 space-y-4">
        <div className="flex items-center justify-between">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Campaign Brief
          </span>
          <span className="text-[11px] font-bold text-orange-600 bg-orange-50 px-2 py-0.5 rounded border border-orange-200">
            Topic Focus
          </span>
        </div>

        <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-2xs">
          <p className="text-base sm:text-lg font-extrabold text-blue-900">
            &ldquo;Digital Marketing Batch 02 — Admissions Open&rdquo;
          </p>
        </div>

        {/* Requirements Checklist */}
        <div>
          <span className="text-[11px] uppercase font-bold text-slate-500 block mb-2 tracking-wider">
            Evaluation Criteria:
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {question.requirements.map((req, i) => (
              <div
                key={i}
                className="flex items-start gap-2 text-xs text-slate-700 bg-white p-2.5 rounded-lg border border-slate-200"
              >
                <CheckSquare className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
                <span>{req}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Submission Link Form */}
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-2xs space-y-4">
        <div className="space-y-1">
          <label
            htmlFor="canvaDesignLink"
            className="block text-xs font-bold uppercase tracking-wider text-slate-700"
          >
            Canva Design Shareable Link <span className="text-slate-400 font-normal">(Public View / Edit URL)</span>
          </label>
          <p className="text-xs text-slate-500">
            Paste the shareable URL generated by Canva for your completed design.
          </p>
        </div>

        <div className="relative">
          <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
            <LinkIcon className="w-4 h-4" />
          </div>
          <input
            id="canvaDesignLink"
            type="url"
            placeholder="https://www.canva.com/design/..."
            value={canvaLink}
            onChange={(e) => {
              onLinkChange(e.target.value);
              setTestedLink(false);
            }}
            className="w-full pl-10 pr-24 py-3 bg-white rounded-lg border border-slate-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-100 text-sm outline-hidden transition-all text-slate-800 shadow-2xs"
          />
          {isValidUrl && (
            <a
              href={canvaLink}
              target="_blank"
              rel="noopener noreferrer"
              onClick={() => setTestedLink(true)}
              className="absolute right-2 top-2 bottom-2 px-3 bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 rounded-md text-xs font-bold flex items-center gap-1 transition-colors"
            >
              <span>Test Link</span>
              <ExternalLink className="w-3 h-3" />
            </a>
          )}
        </div>

        {/* Instructions on how to get Canva link */}
        <div className="p-3.5 rounded-lg bg-blue-50/60 border border-blue-100 flex items-start gap-2.5 text-xs text-slate-600">
          <Info className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
          <div>
            <span className="font-bold text-slate-800">How to get your Canva link:</span> In Canva, click <strong className="text-slate-900">Share</strong> (top right) &rarr; change permissions to <strong className="text-slate-900">&ldquo;Anyone with the link can view&rdquo;</strong> &rarr; click <strong className="text-slate-900">Copy link</strong> &rarr; paste into the field above.
          </div>
        </div>

        {/* Optional design notes */}
        <div className="space-y-1.5 pt-2">
          <label
            htmlFor="designNotes"
            className="block text-xs font-bold uppercase tracking-wider text-slate-700"
          >
            Design Concept Notes <span className="text-slate-400 font-normal">(Optional)</span>
          </label>
          <textarea
            id="designNotes"
            rows={3}
            placeholder="Briefly describe your concept, color choices, typography strategy, or target platform format..."
            value={notes}
            onChange={(e) => onNotesChange(e.target.value)}
            className="w-full p-3.5 bg-white rounded-lg border border-slate-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-100 text-sm outline-hidden transition-all text-slate-800 placeholder:text-slate-400 shadow-2xs"
          />
        </div>
      </div>
    </div>
  );
};

